myapp/src/Entity/Log.php
<?php

namespace App\Entity;

use App\Repository\LogRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LogRepository::class)
 * @ORM\Table(name="ws_log")
 */
class Log
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ip;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $route;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(string $ip): self
    {
        $this->ip = $ip;

        return $this;
    }

    public function getRoute(): ?string
    {
        return $this->route;
    }

    public function setRoute(string $route): self
    {
        $this->route = $route;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

myapp/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="ws_utilisateur")
 */
class User
{
    public const ACTIVE_YES = 1;
    public const ACTIVE_NO = 0;


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank()
     * @Assert\Type("\DateTimeInterface")
     */
    private $birthday;

    /**
     * @ORM\Column(type="boolean", options={"default": 0})
     */
    private $active = self::ACTIVE_NO;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

}

myapp/src/Form/UserFormType.php
<?php


namespace App\Form;


use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class UserFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName', null, [
                'label' => 'Prénom'])
            ->add('lastName', null, [
                'label' => 'Nom'
            ])
            ->add('email', null, [
                'label' => 'Adresse e-mail'
            ])
            ->add('birthday', DateType::class, [
                'label' => 'Date de naissance',
                'widget' => 'single_text'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class
        ]);
    }

}

myapp/src/Controller/UserController.php
<?php


namespace App\Controller;

use App\Entity\User;
use App\Form\UserFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    /**
     * @Route("/", name="homepage")
     */
    public function list(EntityManagerInterface $entityManager): Response
    {
        $repository = $entityManager->getRepository(User::class);
        $users = $repository->findAll();

        return $this->render('user/index.html.twig', [
            'users' => $users,
        ]);
    }

    /**
     * @Route("/user/{id<\d+>}", name="user_show")
     * @param int $id
     * @return Response
     */
    public function show(int $id, EntityManagerInterface $entityManager): Response
    {
        $repository = $entityManager->getRepository(User::class);
        $user = $repository->findOneBy(['id' => $id]);
        if (!$user) {
            throw $this->createNotFoundException(sprintf('No user found for id "%d"', $id));
        }

        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/adm/user/new", name="user_new")
     */
    public function new(EntityManagerInterface $em, Request $request)
    {
       $form = $this->createForm(UserFormType::class);
       $form->handleRequest($request);
       if ($form->isSubmitted() && $form->isValid()) {
           /**  @var User $user */
           $user = $form->getData();
           $user
               ->setActive(User::ACTIVE_YES)
           ;
           $em->persist($user);
           $em->flush();

           $this->addFlash('success', sprintf('L\'utilisateur %s %s a été ajouté avec succès.',
               $user->getFirstName(),
               $user->getLastname()
           ));

           return $this->redirectToRoute('homepage');

       }

       return $this->render('user_admin/new.html.twig', [
           'userForm' => $form->createView()
       ]);

    }

    /**
     * @Route("/adm/user/{id}/edit", name="user_edit")
     */
    public function edit(User $user, Request $request, EntityManagerInterface $em)
    {
        $form = $this->createForm(UserFormType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var User $user */
            $user = $form->getData();
            $em->persist($user);
            $em->flush();
            $this->addFlash('success', 'L\'utilisateur a été modifié !');
            return $this->redirectToRoute('homepage');
        }
        return $this->render('user_admin/new.html.twig', [
            'userForm' => $form->createView()
        ]);
    }

    /**
     * @Route("/adm/user/{id<\d+>}/del", name="user_remove")
     * @param int $id
     * @return Response
     */
    public function remove(int $id, EntityManagerInterface $em): Response
    {
        $repository = $em->getRepository(User::class);
        $user = $repository->findOneBy(['id' => $id]);
        if (!$user) {
            throw $this->createNotFoundException(sprintf('Aucun utilisateur trouvé avec l\'id "%d"', $id));
        }
        $user->setActive(User::ACTIVE_NO);
        $em->persist($user);
        $em->flush();

        $this->addFlash('success', 'L\'utilisateur a été désactivé !');

        return $this->redirectToRoute('homepage');
    }
}

myapp/templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Bienvenue !{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Spartan&display=swap">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-light bg-light ">
    <a class="navbar-brand" href="{{ path('homepage') }}">
        <p class="pl-2 d-inline font-weight-bold" style="color: #444;">Treezor test</p>
    </a>
</nav>
{% block body %}{% endblock %}
<footer class="mt-5 p-3 text-center">
    Une réalisation de C. DE BRUYNE
</footer>
{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>

myapp/templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="jumbotron-img jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Liste des utilisateurs</h1>
        </div>
    </div>
    <div class="container">
        {% for message in app.flashes('success') %}
            <div class="row justify-content-center">
                <div class="col-8">
                    <div class="alert alert-success">
                        {{ message }}
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="row mb-3">
            <div class="col text-right">
                <a href="{{ path('user_new') }}" ><button class="btn btn-p">Ajouter un utilisateur</button></a>
            </div>
        </div>
        <div class="row">
            <table class="table table-hover user-list-table">
                <thead>
                <tr>
                    <th scope="col">Prénom</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Email</th>
                    <th scope="col">Date de naissance</th>
                    <th scope="col" class="text-center">Actif</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.firstname }}</td>
                        <td>{{ user.lastname }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.birthday|date('d/m/Y') }}</td>
                        <td class="text-center">
                            <span class="fa fa-{{ user.active ? 'check text-success' : 'times text-danger' }}"></span>
                        <td>
                            <a href="{{ path('user_show', {'id': user.id}) }}"><button class="btn btn-sm"><span class="fa fa-eye"></span></button></a>
                            {% if user.active %}
                                <a href="{{ path('user_edit', {'id': user.id}) }}"><button class="btn btn-sm"><span class="fa fa-edit"></span></button></a>
                                <button class="btn btn-sm" data-toggle="modal" data-target="#userRemove{{ user.id }}"><span class="fa fa-trash"></span></button>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% for user in users %}
        <!-- Modal -->
        <div class="modal fade" id="userRemove{{ user.id }}" tabindex="-1" aria-labelledby="userRemoveModal" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Suppression de l'utilisateur</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Êtes-vous sûr de vouloir supprimer cet utilisateur ?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Fermer</button>
                        <a href="{{ path('user_remove', {'id': user.id}) }}"><button type="button" class="btn btn-p">Supprimer</button></a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

myapp/templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition de l'Utilisateur: {{ user.firstname }} {{ user.lastname }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="card mt-3">
                    <div class="card-header">
                        <h5 class="card-title">Détail de l'utilisateur</h5>
                    </div>
                    <div class="card-body">
                        <div class="card-text">
                            <div class="row">
                                <div class="col">
                                    Prénom : {{ user.firstName }}
                                </div>
                                <div class="col">
                                    Nom : {{ user.lastname }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    E-mail : {{ user.email }}
                                </div>
                                <div class="col">
                                    Date de Naissance : {{ user.birthday|date("d/m/Y") }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button type="button" class="btn btn-outline-secondary mr-2" onClick="window.history.back();">Retour</button>
                        {% if user.active %}
                            <a href="{{ path('user_edit', {'id': user.id}) }}"><button class="btn btn-p">Modifier</button></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

myapp/templates/user_admin/new.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="jumbotron-img jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Ajout d'un nouvel utilisateur</h1>
        </div>
    </div>
    <div class="container">
        {{ form_start(userForm) }}
        {{ form_widget(userForm) }}
        <div class="col text-right p-0">
            <button type="button" class="btn btn-outline-secondary mr-2" onClick="window.history.back();">Retour</button>
            <button type="submit" class="btn btn-p">Enregistrer</button>
        </div>
        {{ form_end(userForm) }}
    </div>
{% endblock %}

myapp/templates/utilisateur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur: {{ utilisateur }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="my-4">Détail de l'utilisateur</h2>
                <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                    <div class="q-container-show p-4">
                        <div class="row">
                            <div class="col">
                                <h1 class="q-title-show">{{ utilisateur }}</h1>
                                <div class="q-display p-3">
                                    <i class="fa fa-quote-left mr-3"></i>
                                    <p class="d-inline">I've been turned into a cat, any thoughts on how to turn back? While I'm adorable, I don't really care for cat food.</p>
                                    <p class="pt-4"><strong>--Tisha</strong></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}